# Generated by Django 5.1.2 on 2024-10-31 06:58

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_time_create_goods_time_update_alter_goods_cats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='goods',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddIndex(
            model_name='goods',
            index=models.Index(fields=['-time_create'], name='goods_goods_time_cr_cf3877_idx'),
        ),
    ]
