# Generated by Django 5.1.2 on 2024-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goods_options_goods_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
