# Generated by Django 5.1.2 on 2024-11-24 17:37

import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goods_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.BooleanField(default=0, verbose_name=goods.models.Goods.Status),
        ),
    ]
