# Generated by Django 5.1.2 on 2025-01-15 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_category_remove_goods_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='cats',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.category'),
        ),
    ]
