# Generated by Django 5.1.2 on 2025-01-20 14:43

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_goods_cats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='tag')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='cats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.category'),
        ),
        migrations.AddField(
            model_name='goods',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='goods.tags'),
        ),
    ]
