# Generated by Django 5.1.2 on 2025-01-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_tags_alter_goods_cats_goods_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='gtags', to='goods.tags'),
        ),
    ]
