# Generated by Django 5.1.2 on 2025-02-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_uploadfiles_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
